
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 26 00:53:41 BRST 2015
//----------------------------------------------------

package jflex_plft5;

/** CUP generated interface containing symbol constants. */
public interface CodSym {
  /* terminals */
  public static final int IDENTIFICADOR = 84;
  public static final int AP = 72;
  public static final int REAL = 55;
  public static final int MAIOR_QUE = 67;
  public static final int MENOR_QUE = 64;
  public static final int PACKED = 10;
  public static final int TYPE = 16;
  public static final int READ = 53;
  public static final int CONST = 29;
  public static final int ASM = 17;
  public static final int DIVR = 79;
  public static final int ACHAVE = 74;
  public static final int UNTIL = 23;
  public static final int CONSTRUCTOR = 35;
  public static final int DIFERENTE = 83;
  public static final int ATRIBUICAO = 76;
  public static final int FP = 73;
  public static final int INTEGER = 54;
  public static final int DOUBLE = 57;
  public static final int SUB = 81;
  public static final int SHR = 42;
  public static final int FALSE = 60;
  public static final int NOT = 37;
  public static final int NIL = 31;
  public static final int ARRAY = 12;
  public static final int OBJECT = 41;
  public static final int SHL = 38;
  public static final int VAR = 13;
  public static final int INLINE = 14;
  public static final int FLOAT = 56;
  public static final int THEN = 5;
  public static final int GOTO = 40;
  public static final int RECORD = 22;
  public static final int MOD = 26;
  public static final int MAIORIGUAL = 66;
  public static final int WRITE = 52;
  public static final int TRUE = 59;
  public static final int IGUAL = 70;
  public static final int UNIT = 19;
  public static final int PONTO = 82;
  public static final int WHILE = 43;
  public static final int IMPLEMENTATION = 49;
  public static final int INTERFACE = 18;
  public static final int CHAR = 61;
  public static final int BOOLEAN = 58;
  public static final int DP = 68;
  public static final int DO = 48;
  public static final int FOR = 25;
  public static final int PV = 69;
  public static final int DIV = 44;
  public static final int MULT = 78;
  public static final int DOWNTO = 8;
  public static final int ELSE = 6;
  public static final int PO = 77;
  public static final int PROCEDURE = 15;
  public static final int EOF = 0;
  public static final int VG = 71;
  public static final int FOWARD = 30;
  public static final int FUNCTION = 36;
  public static final int REPEAT = 27;
  public static final int LABEL = 21;
  public static final int MENORIGUAL = 65;
  public static final int ABRECONCHETE = 62;
  public static final int DESTRUCTOR = 39;
  public static final int IN = 9;
  public static final int OR = 50;
  public static final int SET = 32;
  public static final int error = 1;
  public static final int IF = 28;
  public static final int OF = 45;
  public static final int END = 7;
  public static final int NUMERO_INTEIRO = 85;
  public static final int NUMERO_REAL = 86;
  public static final int ANY = 2;
  public static final int FILE = 20;
  public static final int SOMA = 80;
  public static final int FECHACONCHETE = 63;
  public static final int BEGIN = 4;
  public static final int CASE = 24;
  public static final int FCHAVE = 75;
  public static final int STRING = 46;
  public static final int PROGRAM = 3;
  public static final int AND = 34;
  public static final int TO = 11;
  public static final int WITH = 47;
  public static final int USES = 33;
  public static final int XOR = 51;
}

