
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 25 15:20:21 GMT-03:00 2015
//----------------------------------------------------

package jflex_plft5;

/** CUP generated interface containing symbol constants. */
public interface CodSym {
  /* terminals */
	public static final int ANY = 100;
    public static final int EOF = 0;
    public static final int PROGRAM = 1;
    public static final int BEGIN = 2;
    public static final int IDENTIFICADOR = 3;
    public static final int THEN = 4;
    public static final int ELSE = 5;
    public static final int END = 6;
    public static final int DOWNTO = 7;
    public static final int IN = 8;
    public static final int PACKED = 9;
    public static final int TO = 10;
    public static final int ARRAY = 11;
    public static final int VAR = 12;
    public static final int INLINE = 13;
    public static final int PROCEDURE = 14;
    public static final int TYPE = 15;
    public static final int ASM = 16;
    public static final int INTERFACE = 17;
    public static final int UNIT = 18;
    public static final int FILE = 19;
    public static final int LABEL = 20;
    public static final int RECORD = 21;
    public static final int UNTIL = 22;
    public static final int CASE = 23;
    public static final int FOR = 24;
    public static final int MOD = 25;
    public static final int REPEAT = 26;
    public static final int IF = 27;
    public static final int CONST = 28;
    public static final int FOWARD = 29;
    public static final int NIL = 30;
    public static final int SET = 31;
    public static final int USES = 32;
    public static final int AND = 33;
    public static final int CONSTRUCTOR = 34;
    public static final int FUNCTION = 35;
    public static final int NOT = 36;
    public static final int SHL = 37;
    public static final int DESTRUCTOR = 38;
    public static final int GOTO = 39;
    public static final int OBJECT = 40;
    public static final int SHR = 41;
    public static final int WHILE = 42;
    public static final int DIV = 43;
    public static final int OF = 44;
    public static final int STRING = 45;
    public static final int WITH = 46;
    public static final int DO = 47;
    public static final int IMPLEMENTATION = 48;
    public static final int OR = 49;
    public static final int XOR = 50;
    public static final int WRITE = 51;
    public static final int READ = 52;
    public static final int NUMERO_REAL = 53;
    public static final int NUMERO_INTEIRO = 54;
    public static final int INTEGER = 55;
    public static final int REAL = 56;
    public static final int FLOAT = 57;
    public static final int DOUBLE = 58;
    public static final int BOOLEAN = 59;
    public static final int TRUE = 60;
    public static final int FALSE = 61;
    public static final int CHAR = 62;
    public static final int TEST = 63;
    public static final int ATRIBUICAO = 64;
    public static final int DIFERENTE = 65;
    public static final int MENOR_QUE = 66;
    public static final int MAIOR_QUE = 67;
    public static final int OPERADOR = 68;
    public static final int CONDICIONAL = 69;
    public static final int PONTOS = 70;
    public static final int DELIMITADOR = 90;
    public static final int ABRECONCHETE = 71;
    public static final int FECHACONCHETE = 72;
    public static final int MENORIGUAL = 73;
    public static final int MAIORIGUAL = 74;
    public static final int DP = 75;
    public static final int PV = 76;
    public static final int IGUAL = 77;
    public static final int VG = 78;
    public static final int AP = 79;
    public static final int FP = 80;
    public static final int PO = 81;
    public static final int MULT = 82;
    public static final int DIVR = 83;
    public static final int SOMA = 85;
    public static final int SUB = 86;
    public static final int ACHAVE = 87;
    public static final int FCHAVE = 88;
    public static final int PONTO = 89;
  
}

