
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 16 10:35:17 GMT-03:00 2015
//----------------------------------------------------

package jflex;

/** CUP generated interface containing symbol constants. */
public interface CodSym {
  /* terminals */
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int EOF = 0;
}

