
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 18 13:40:40 GMT-03:00 2015
//----------------------------------------------------

package jflex;

/** CUP generated interface containing symbol constants. */
public interface CodSym {
  /* terminals */
	public static final int EOF = 0;
	public static final int PROGRAM = 1;
	public static final int BEGIN = 2;
    public static final int IDENTIFICADOR = 3;
    public static final int THEN = 4;
    public static final int ELSE = 5;
	public static final int END = 6;
    public static final int DOWNTO = 7;
    public static final int IN = 8;
    public static final int PACKED = 9;
	public static final int TO = 10;
    public static final int ARRAY = 11;
    public static final int VAR = 12;
    public static final int INLINE = 13;
	public static final int PROCEDURE = 14;
    public static final int TYPE = 15;
    public static final int ASM = 16;    
    public static final int INTERFACE = 17;
	public static final int UNIT = 18;
    public static final int FILE = 19;
    public static final int LABEL = 20;
    public static final int RECORD = 21;
	public static final int UNTIL = 22;
    public static final int CASE = 23;
    public static final int FOR = 24;
    public static final int MOD = 25;
	public static final int REPEAT = 26;
    public static final int IF = 27;
    public static final int CONST = 28;
    public static final int FOWARD = 29;
	public static final int NIL = 30;
    public static final int SET = 31;
    public static final int USES = 32;    
    public static final int AND = 33;
	public static final int CONSTRUCTOR = 34;
    public static final int FUNCTION = 35;
    public static final int NOT = 36;
    public static final int SHL = 37;
	public static final int DESTRUCTOR = 38;
    public static final int GOTO = 39;
    public static final int OBJECT = 40;
    public static final int SHR = 41;
	public static final int WHILE = 42;
    public static final int DIV = 43;
    public static final int OF = 44;
    public static final int STRING = 45;
	public static final int WITH = 46;
    public static final int DO = 47;
    public static final int IMPLEMENTATION = 48;    
    public static final int OR = 49;
	public static final int XOR = 50;
    
  
}

